Data Population Scripts
UoA-Discords/api pull request #6
Opened 2022-08-31 05:04 UTC by NachoToast

Adds a script for populating the user database and entries databases with random values.

Goes above just random generation, as all data will also be valid:
- Time strings of certain events will always be chronologically after time strings of dependent events (e.g. if `userA` made `applicationA`, `userA.firstLogin` will be before `applicationA.createdAt`.
- IDs will follow Discord's Snowflake ID format.
- Member count history will be somewhat continuous (utilizing `sin` and `cos` functions).
- Invite codes will be syntactically valid.
- Usernames all follow a basic `<adjective><noun>` grammar.
- Dates will never be from before 1/1/2021.

Notably:
- IDs are not guaranteed to be unique upon generation, however duplicate IDs get overwritten (by whichever one was generated later) so this isn't a cause for concern.
- User avatars are always `null`, since it is not feasible to generate these without using actual Discord users.
- IP addresses may be reserved, i.e. it is possible for the value `255` to occur.

2022-08-31 06:04 UTC, pumbas600 approved these changes
LGTM, I  just added a few suggestions

2022-09-01 00:05 UTC, NachoToast commented
Currently blocked by:
- https://github.com/UoA-Discords/shared/pull/1

2022-09-01 08:23 UTC, NachoToast commented on scripts/population/helpers/entryGen.ts
> +
Yeah so what happened was I made the 3 to 7 (inclusive) code and comment, then I thought "hmm pretty sure they can be longer than that" so I looked at some from the live site. After seeing some longer ones I decided to up it to 10 and changed the comment, but totally forgot to change to code. 😆

2022-09-01 08:24 UTC, NachoToast commented on scripts/population/helpers/entryGen.ts
> +}
Nope, stuck in the mindset of being unable to refer to properties of unitialized objects, but that isn't true for arrays :P

2022-09-01 08:26 UTC, NachoToast commented on scripts/population/populateDatabases.ts
> +};
I cannot find a way to do this without errors occurring, do you have an example implementation?

2022-09-02 02:36 UTC, NachoToast commented on scripts/population/helpers/entryGen.ts
> +    }
We don't allow assigning directly to undefined for `optional?` variables.
Via `tsconfig.json`:
```json
    "exactOptionalPropertyTypes": true,               /* Interpret optional property types as written, rather than adding 'undefined'. */
```

This is outdated anyways since the new model says `inviteCreatedBy` is nullable, not optional.

2022-09-02 03:44 UTC, NachoToast commented on scripts/integrity/adminStats.ts
> +        }
I need to add removal from `OptOutDatabase` here too, oops.

2022-09-02 14:16 UTC, pumbas600 commented on scripts/population/populateDatabases.ts
> +};
Ah, apparently it's only compatible with ES2015 and higher (Not ES5 which is what we're using)

2022-09-02 14:31 UTC, pumbas600 requested changes
Just a few small changes :)

2022-09-02 14:31 UTC, pumbas600 commented on scripts/integrity/adminStats.ts
> +                addIfNonExistent(guild.stateActionDoneBy?.id ?? `AUTOMATED`, state);
If I recall correctly, this non-null assertion operator is not required here anymore?

2022-09-02 14:31 UTC, pumbas600 commented on scripts/integrity/usersExist.ts
> +            const action = `${EntryStates[entry.state]!.toLowerCase()} by`;
I also don't think `!` is required here either?

2022-09-02 14:31 UTC, pumbas600 commented on scripts/population/helpers/genHelpers.ts
> +
Is this meant to be `nouns.length`?

2022-09-02 14:31 UTC, pumbas600 commented on scripts/population/helpers/userGen.ts
> +    const discriminator = randomId(4);
I've seen you use `usernameNoun.slice(0, 1).toUpperCase() + usernameNoun.slice(1)` to capitalise the string several times now, maybe create a utility helper method instead. It'll also help with readability because I don't think the fact that this is capitalising the string is immediately obvious.

2022-09-02 14:31 UTC, pumbas600 commented on scripts/population/populateDatabases.ts
> +
Are these non-null assertion operators necessary?

2022-09-03 03:35 UTC, NachoToast commented on scripts/population/populateDatabases.ts
> +
[6ed2fe2](https://github.com/UoA-Discords/api/pull/6/commits/6ed2fe2158c8d44575168d72ac48c34808393ab7)

2022-09-03 03:35 UTC, NachoToast commented on scripts/integrity/usersExist.ts
> +            const action = `${EntryStates[entry.state]!.toLowerCase()} by`;
[6ed2fe2](https://github.com/UoA-Discords/api/pull/6/commits/6ed2fe2158c8d44575168d72ac48c34808393ab7)

2022-09-03 03:36 UTC, NachoToast commented on scripts/population/helpers/genHelpers.ts
> +
89cddf7

2022-09-03 03:36 UTC, NachoToast commented on scripts/population/helpers/userGen.ts
> +    const discriminator = randomId(4);
701fcdc

2022-09-03 03:36 UTC, NachoToast commented on scripts/integrity/adminStats.ts
> +                addIfNonExistent(guild.stateActionDoneBy?.id ?? `AUTOMATED`, state);
6ed2fe2

2022-09-03 03:37 UTC, NachoToast commented on scripts/population/populateDatabases.ts
> +};
We're using ES2022 though.

2022-09-03 04:58 UTC, pumbas600 commented on scripts/population/populateDatabases.ts
> +};
Oh whoops, I was looking at the website tsconfig.

I don't get any errors with this in the backend:
```ts
const map = new Map<number, string>([
    [1, "Val 1"],
    [2, "Val 2"],
]);

for (const key of map.keys()) {
    // key is of type number
}
```

2022-09-03 05:01 UTC, pumbas600 approved these changes
LGTM :)

2022-09-03 05:02 UTC, pumbas600 commented
lol, apparently my review doesn't count to let you merge

2022-09-03 05:08 UTC, NachoToast commented
> lol, apparently my review doesn't count to let you merge

Yeah I forgot to add you to the backend team, you should see the invite now.

2022-09-03 05:18 UTC, NachoToast commented
Maps seem to be having more issues.
![image](https://user-images.githubusercontent.com/32235595/188256951-60a97dd5-b5df-4024-81ab-1b031b0704b0.png)

2022-09-03 05:24 UTC, pumbas600 commented
> Maps seem to be having more issues.

You can't access values from a map using `[key]` you need to use `map.get(key)`. It does potentially return undefined though, so you would have to use `!`. That being said, `Record` works too.

2022-09-03 05:38 UTC, merged